# Specify where you want to store the database
# NOTE: Follow this format
db_url = "sqlite:///path/to/sqlite.db"
# Specify full path for the player to use
player_path = "/path/to/player"

# Specify playlists in the following way
# NOTE: multiple playlists are supported!
[[playlists]]
url = "https://example.com/playlist1.m3u"
name = "Playlist 1"

[[playlists]]
url = "https://example.com/playlist2.m3u"
name = "Playlist 2"
