name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["*"]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Apt packages
        run: sudo apt-get update

      - name: Setup | Rust toolchain
        uses: dtolnay/rust-toolchain@1.70.0
        with:
          components: clippy, rustfmt

      - name: Setup | Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Setup | Just
        uses: extractions/setup-just@v2

      - name: Hygiene | Formatting
        run: just fmt

      - name: Hygiene | Clippy
        run: just clippy

      - name: Hygiene | Test
        run: just test

      - name: Hygiene | Build
        run: just build-dev
